#!/bin/bash

# 🚀 Railway Deployment Automation Script
# This script guides you through connecting your GitHub repo to Railway
# and configuring automatic deployments

echo "🚀 EcoDash Railway Deployment Guide"
echo "===================================="
echo ""
echo "✅ Your code has been pushed to GitHub!"
echo "Repository: https://github.com/ary0912/EcoDash"
echo ""
echo "📋 Follow these steps to deploy to Railway:"
echo ""
echo "STEP 1: Go to Railway"
echo "  👉 Visit: https://railway.app"
echo ""
echo "STEP 2: Create Account or Sign In"
echo "  - Click 'Sign Up' or 'Sign In'"
echo "  - Authorize with GitHub"
echo ""
echo "STEP 3: Create New Project"
echo "  - Click 'Create New Project'"
echo "  - Select 'Deploy from GitHub repo'"
echo "  - Click 'Configure GitHub App' (if needed)"
echo "  - Select 'ary0912/EcoDash' repository"
echo "  - Click 'Deploy Now'"
echo ""
echo "STEP 4: Wait for Initial Deploy"
echo "  - Railway will auto-detect Node.js monorepo"
echo "  - It will create a service and start building"
echo "  - First deployment takes 2-5 minutes"
echo ""
echo "STEP 5: Configure Service Settings"
echo "  Once deployed, go to your service 'Settings' tab:"
echo ""
echo "  Build Command:"
echo "    npm install && npm run build"
echo ""
echo "  Start Command:"
echo "    npm start"
echo ""
echo "  Environment Variables:"
echo "    NODE_ENV = production"
echo "    PORT = 3000"
echo ""
echo "STEP 6: Verify Deployment"
echo "  - Go to your service 'Deployments' tab"
echo "  - Copy your Railway URL (e.g., https://ecodash.up.railway.app)"
echo "  - Visit the URL in your browser"
echo "  - You should see your app!"
echo ""
echo "🎉 That's it! Your app is live!"
echo ""
echo "📊 Auto-Deployment:"
echo "  - Every push to 'main' branch auto-deploys"
echo "  - Deployment takes 1-2 minutes"
echo "  - Check 'Deployments' tab to monitor"
echo ""
echo "💡 Tips:"
echo "  - Monitor logs in 'Deployments' → 'Logs' tab"
echo "  - View real-time metrics in 'Metrics' tab"
echo "  - Add custom domain in 'Settings' tab"
echo ""
echo "❓ Issues?"
echo "  - Check deployment logs for errors"
echo "  - Verify NODE_ENV=production is set"
echo "  - Ensure all env variables are configured"
echo ""
